### ISSUE TITLE
Working with WHMCS Version 6.3.1

### ISSUE THREAD

**Issue by dazzert** [SpectroFinance/SpectroCoin-Merchant-WHMCS#1]
Hi does this work with WHMCS Version    6.3.1.I have uploaded the addon and i cant see the addon on the addon section nor can i find "Bitcoin provided by SpectroCoin" in the Payment Gateways section.

**Comment by Karciukass** [comment]
Hello,
What version of WHMCS you are using now?
If you are using V6.3.1 it does not work now it will be fixed about one month later, sorry for inconvenience.
Regards,
Karolis

**Comment by Karciukass** [comment]
Hello,
Now you can use WHMCS with 6.3.1 Version. If you get any problems you can write for us: info@spectrocoin.com
Regards,
SpectroCoin Team

**Comment by dazzert** [comment]
Excellent, I will give it a go, I am still running V6.3.1 .Much appreciated

**Comment by dazzert** [comment]
Its Tested and working many thanks. Here is the Install Video for those wanting to install makes the setup a Breeze.
https://blog.spectrocoin.com/2016/07/spectrocoin-merchant-integration-to-whmcs-tutorial/
